### ISSUE TITLE
Where do you input the Bookstack URL

### ISSUE THREAD

**Issue by dCdUP** [ngearhart/confluence-to-bookstack-migrate#1]
Hello, 

im am trying to migrate a confluence server to a bookstack server. Is it possible that you give me a how to or an instruction set to use your script? I am confused as to where the bookstack instance comes into play, since everything I can read from the sourcecode seems to do only confluence exportation of the pages but does not import them into bookstack. pls help

**Comment by ngearhart** [comment]
This project is not production ready yet
